### ISSUE TITLE
Pay the hourly rate for the hours up to 40 and 1.5 times the hourly rate for all hours worked above 40 hours.

### ISSUE THREAD

**Issue by KelorHub** [tsugiproject/tsugi#109]
https://www.py4e.com/ 
Autograder Ex 3.1

In this sentence:"Pay the hourly rate for the hours up to 40 and **1.5** times the hourly rate for all hours worked above 40 hours." 
(1.5 is wrong) to get the 498.75 as requested you must multiply by 0.5 times and not 1.5.

**Comment by Vanish565** [comment]
you read the question wrong, you have to multiply 1.5 to the 10.50 hourly rate for every extra hour of overtime.
