### ISSUE TITLE
Database upgrade not working if $CFG->dbprefix is set

### ISSUE THREAD

**Issue by torinfo** [tsugiproject/tsugi#112]
If $CFG-dbprefix is set and columns need to be added, the table name is wrong in th eupgrade SQL, because the $CFG->dbprefix is prepended twice (at least in two locations)

admin/lti/database.php cf lines 690-704:  $CFG->dbprefix is added on line 696 and on 700. As a test removed it on line 700.

Similar issue in admin/blob/database.php lines 95 - 109

**Comment by csev** [comment]
Fixed in 5fa3031bf12bcc884e8295dc86f8fcacc666ce37
