### ISSUE TITLE
Deprecated warning on PHP8

### ISSUE THREAD

**Issue by torinfo** [tsugiproject/tsugi#117]
Deprecated: Required parameter $dir follows optional parameter $filename in /var/www/html/tsugi/admin/admin_util.php on line 233

At least I think it is because of PHP 8. I installed the latest master.

**Comment by csev** [comment]
Thanks - I merged the dependencies branch before I fixed this - so you will see a lot on your next git pull.   But this was an easy fix - thanks for the catch - and for testing PHP 8 :)

**Comment by torinfo** [comment]
That fixed it :-)
