### ISSUE TITLE
Plans to update to codemirror6?

### ISSUE THREAD

**Issue by krishnakumarg1984** [tsugiproject/tsugi#127]
The upcoming Codemirror 6 is a complete re-write from scratch. I was wondering if your py4e autograder shall adopt codemirror6 whenever it is released?

**Comment by csev** [comment]
I would be happy to upgrade to CodeMirror 6 when the time is right.  This PR belongs in the PY4E repo though:

https://github.com/csev/py4e

**Comment by krishnakumarg1984** [comment]
Thank you.
