### ISSUE TITLE
PHP 8.X function libxml_disable_entity_loader is deprecated

### ISSUE THREAD

**Issue by torinfo** [tsugiproject/tsugi#134]
This causes a warning on line 13 of vendor/tsugi/lib/include/setup.php

I solved it in the Xerte code by adding  '&& \PHP_VERSION_ID < 8000'

So the whole line reads as:

if ( function_exists ( 'libxml_disable_entity_loader' )  && \PHP_VERSION_ID < 8000) libxml_disable_entity_loader();

**Comment by csev** [comment]
This has been fixed - thanks.
