### ISSUE TITLE
Deprecated: Automatic conversion of false to array (PHP 8.1)

### ISSUE THREAD

**Issue by TurRil** [tsugiproject/tsugi#148]
[tsugi]/admin/external/?search_text=none

When showing "Nothing to display." the page displays the following:

Deprecated: Automatic conversion of false to array is deprecated in /var/www/vhosts/tsugi-tools.uct.ac.za/vendor/tsugi/lib/src/UI/Table.php on line 92

**Comment by raikageray011** [comment]
yeah

**Comment by csev** [comment]
This was fixed in the PHP 8.2 work and now in master.
