### ISSUE TITLE
Make Tsugi work on PHP 8.2

### ISSUE THREAD

**Issue by csev** [tsugiproject/tsugi#155]
Some of the Tsugi core code generates warnings under PHP 8.2.   It would be nice if Tsugi came up under PHP 82 and ran without error.

**Comment by csev** [comment]
It is already in progress.

**Comment by ottenhoff** [comment]
PHP 7.4 is now EOL. Why not move PHP 8 branch into master?

https://www.php.net/supported-versions.php

**Comment by csev** [comment]
This is now in master and working nicely.   The biggest problem was functions line strlen() and htmlentities() freaking out if their parameter was a null or false.  Sigh.
