### ISSUE TITLE
Missing Ellipses in store markup

### ISSUE THREAD

**Issue by csev** [tsugiproject/tsugi#160]
Hey @andrewniekamp - Sakai QA was  doing some testing and noticed this:

When adding a tool, I see the following console errors:
[sakai.tsugicloud.org/:1064](http://sakai.tsugicloud.org/:1064) 
GET https://sakai.tsugicloud.org/tsugi/lti/store/static/ftellipsis.js net::ERR_ABORTED 403

[sakai.tsugicloud.org/:1149](http://sakai.tsugicloud.org/:1149) 
        
       Uncaught ReferenceError: Ellipsis is not defined
    at [sakai.tsugicloud.org/:1149:24](http://sakai.tsugicloud.org/:1149:24)
    at HTMLCollection.forEach (<anonymous>)
    at [sakai.tsugicloud.org/:1148:13](http://sakai.tsugicloud.org/:1148:13)

**Comment by andrewniekamp** [comment]
Ah I see, it looks like I missed that library from the LTI store side. I see the Ellipsis js file is currently within tsugi at tsugi/store/static - does it sound alright to move that js file to tsugi-static and then reference it from there in both app stores?

**Comment by csev** [comment]
Yes - that would be the best strategy.
