### ISSUE TITLE
Write a Python version of Tsugi

### ISSUE THREAD

**Issue by csev** [tsugiproject/tsugi#23]
This is something that is waiting for someone with interest and willingness to put the resulting code in production.

**Comment by arshadsid** [comment]
Sir,

By python version you mean a python applications instead of all the php or something else?

**Comment by csev** [comment]
I want to wait until someone will run the Python library - so it is regularly tested.

**Comment by csev** [comment]
So I am closing this.   I built a way to build Tsugi tools in Django through a gateway.  But it seems that after I built a better mouse trap - no one but me cared.  I have an LTI tool for my Django for Everybody course in production in Django.   But after doing and building it - my feeling is "meh".  The gateway is not and solid and quite easy to extend - bit someone other than me should care about it for it to go mainstream.

**Comment by jonespm** [comment]
Yeah, the longer you wait, the less useful "re-writing X in X" becomes! I've wanted to use the Tsugi Django but just never had a project that it fit in, and went with regular LTI packages. Might even be moving over to Node.js based frameworks.
