### ISSUE TITLE
Remove vendor folder from repository

### ISSUE THREAD

**Issue by EricTendian** [tsugiproject/tsugi#30]
Hi, I'm a new user of Tsugi and I noticed that this project has the `vendor` directory included in the repository. I recommend it should be removed and added to the `.gitignore` file, per the best practices described in ["Should I commit the dependencies in my vendor directory?"](
https://getcomposer.org/doc/faqs/should-i-commit-the-dependencies-in-my-vendor-directory.md) I can make a new PR with the changes and update the docs if maintainers want this.

Is there some reasoning I'm missing for including it in the repository?

**Comment by csev** [comment]
The reasoning has been all along to keep things simple with a single git checkout.   But recently as I have started to evolve to using Silex, the vendor folder is getting messy (it used to be only the tsusi-php library) it is probably to switch to the best practice.

My plan is to do more refactoring into silex while maintaining the pre-silex code like lessons.php and badges.php - and then make a tag and minor release and then after that minor release delete the pre-silex code and get rid of the vendor folder.

Sooo.   It is coming after the next minor release.

**Comment by csev** [comment]
So we have been living with the vendor branch in the repo - and given the complex intricacies of how Composer can follow itself down a rabbit hole and break everything - it is probably just as well to keep things the way they are.  It is complex for developers and maintainers - but great for those in production.  It means no need to install, run or debug composer ever.
