### ISSUE TITLE
Removing sample keys

### ISSUE THREAD

**Issue by mlhess** [tsugiproject/tsugi#67]
## Issue
On/admin/key/keys  there are some keys that come installed by default.  I wanted to remove them so I did.

However, after removing all the keys, it blocks the creation of a new key

```
?php if ( count($newrows) < 1 ) { ?>
<p>
You have no Tenant keys for this system.
</p>
<?php } else {
    $extra_buttons = array(
        "Insert New Key" => "key-add"
    );
    Table::pagedTable($newrows, $searchfields, false, "key-detail", false, $extra_buttons);
}
if ( isAdmin() ) { ?>
<?php } ?>


```
## excepted result
You should always be able to add keys even if you have no keys in your database.

**Comment by jonespm** [comment]
Makes sense to me, I put a PR in for it on #73
