### ISSUE TITLE
Security issue: terrible xss attack vector in "output.php" file

### ISSUE THREAD

**Issue by mortezasaki** [tsugiproject/tsugi#70]
Dear dev,
If you are echoing into JS inside a HTML document (as you are in your example), you risk opening up a huge XSS vulnerability.
```php
echo('            context_title: '.json_encode($CONTEXT->title).",\n");
...
```
you must use "JSON_HEX_TAG" in the json_encode function.
instead of above code you must use below:
```php
echo('            context_title: '.json_encode($CONTEXT->title).",\n",JSON_HEX_TAG);
...
```

https://security.stackexchange.com/questions/175630/passing-php-code-directly-into-javascript-in-html5
https://stackoverflow.com/questions/20942452/why-does-script-cause-a-dom-tree-break-on-the-browser
https://security.stackexchange.com/questions/110101/proper-way-to-protect-against-xss-when-output-is-directly-into-js-not-html

**Comment by csev** [comment]
Thanks.  Do you want to make a Pull request or should I just fix this?

/Chuck

**Comment by mortezasaki** [comment]
you can fix this.

**Comment by csev** [comment]
This is fixed in 80ca6b499b7a1fbd9481f62f379a19709fad5e02 - take a look and see what you think.  Thanks.

**Comment by mortezasaki** [comment]
thank for fix it. now it's safe

**Comment by ziaulrehman40** [comment]
Issue should be closed
