### ISSUE TITLE
Help I need help with this. 

### ISSUE THREAD

**Issue by darkaura102** [tsugiproject/tsugi#75]
largest = 0
smallest = 0

while True:
    num = input("Enter a number: ")
    if num == "done" :
        break
    try:
        num == float (num)  
    except:
        print ("Invalid input")
         
#############
 
if num > largest:
    num is largest
    print("Maximum is num")

if num < smallest:
        num is smallest
        print("Minimum is smallest")

*Im not sure but I have been working on this for awhile.  I need the result to read:
Invalid input
Maximum is 10
Minimum is 2

**Comment by darkaura102** [comment]
*I'm not sure but I have been working on this for a while. I need the result to read:
Invalid input
Maximum is 10
Minimum is 2
* I believe my hiccup is with the minimum and maximum print statements

**Comment by csev** [comment]
This list is not the place to ask questions about my Python courses.   Sorry.

**Comment by darkaura102** [comment]
I was just asking for someone to explain how, not the answer. I have been
working on this one question for 2 years. I have asked on your forum as
well. They didnt understand what i was talking about. No bad intentions
here, just self teaching and learning a new skill. I apolagize for that and
will keep asking in your forum only.

**Comment by 561shubham** [comment]
My code is:

largest = None

smallest = None

while True:

num = input("Enter a number: ")

if num == "done" : break

try:

test == int(num)

except:

print("Invalid input")

if num > largest:

print("Maximum is", num)

if num < smallest:

print("Minimum is", num)


 I want output to be:

Invalid input
Maximum is 10
Minimum is 2

please do help
