### ISSUE TITLE
7.1 Write a program that prompts for a file name, then opens that file and reads through the file, and print the contents of the file in upper case. Use the file words.txt to produce the output

### ISSUE THREAD

**Issue by tamilselvav-jaganathan** [tsugiproject/tsugi#80]
ame = raw_input("Enter file name: ")

fh = open(fname)
for i in fh:
   fh = i.upper()
   print fh.rstrip()

**Comment by jonespm** [comment]
This repository is for issues related to Tsugi, not for other issues.
