### ISSUE TITLE
Doesn't work:  PEP 498 -- Literal String Interpolation

### ISSUE THREAD

**Issue by Falnesio** [tsugiproject/tsugi#91]
f string literals won't work in https://www.py4e.com/tools

![image](https://user-images.githubusercontent.com/36005374/88728303-c4813600-d107-11ea-8772-9aacbff1c38e.png)

https://www.python.org/dev/peps/pep-0498/

**Comment by csev** [comment]
Wow - We use an underlying product to run Python in the browser called Skulpt.   Let me look into making f-strings work - it is non-trivial.  Lets keep this open.

**Comment by csev** [comment]
https://github.com/skulpt/skulpt/pull/975

**Comment by csev** [comment]
This issue really belongs in https://github.com/csev/py4e
